version: '3.9'

services:
#  api:
##    image: api
##    build:
##      context: .
##      dockerfile: Dockerfile
##    ports:
##      - '5000:80'
  rabbitmq:
    image: rabbitmq:3.11.7-management
    container_name: Queue
    volumes: 
        - rabbitmq-data:/var/lib/rabbitmq
        - rabbitmq-data:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # Port dla AMQP
      - "15672:15672"  # Port dla Management UI
    
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'

  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=qwerty
      - MINIO_ROOT_PASSWORD=1qazxsw@
    command: server --console-address ":9001" --address ":9000" /data


volumes:
  minio_data:
    driver: local
  rabbitmq-data:
 
